"""empty message

Revision ID: 536447be432c
Revises: acb7e2d2001e
Create Date: 2018-04-24 14:46:21.886399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536447be432c'
down_revision = 'acb7e2d2001e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'story_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_stories')
    # ### end Alembic commands ###
